name:                streamly-lmdb
version:             0.5.0
github:              "shlok/streamly-lmdb"
license:             BSD3
author:              "Shlok Datye"
maintainer:          "sd-haskell@quant.is"
copyright:           "2022 Shlok Datye"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Stream data to or from LMDB databases using the streamly library.
category:            Database, Streaming, Streamly

description:         Please see the README on GitHub at <https://github.com/shlok/streamly-lmdb#readme>

dependencies:
- async >= 2.2.2 && < 2.3
- base >= 4.7 && < 5
- bytestring >= 0.10.10.0 && < 0.11
- streamly >= 0.8 && < 0.9

ghc-options:
- -Wall

extra-libraries:
- lmdb

library:
  source-dirs: src
  c-sources: src/Streamly/External/LMDB/Internal/streamly_lmdb_foreign.c
  install-includes: src/Streamly/External/LMDB/Internal/streamly_lmdb_foreign.h
  include-dirs: src/Streamly/External/LMDB/Internal

tests:
  streamly-lmdb-test:
    main:                TestSuite.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory >= 1.3.6.0 && < 1.4
    - QuickCheck >= 2.13.2 && < 2.15
    - streamly-lmdb
    - tasty >= 1.2.3 && < 1.5
    - tasty-quickcheck >= 0.10.1.1 && < 0.11
    - temporary >= 1.3 && < 1.4
