name: CI
on:
  push:
    branches:
      - master
      - wip
  pull_request:
    types:
      - opened
      - synchronize

  # Allows us to run the workflow manually from the Actions tab.
  workflow_dispatch:

  schedule:
    - cron: '0 2 1 * *' # At 02:00 on day-of-month 1.
jobs:
  flake:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: nix build -L .#streamly-lmdb-ci
